### ISSUE TITLE
Sort drop-down overlaps the site count on smaller widths

### ISSUE THREAD

**Issue by m-i-l** [searchmysite/searchmysite.net#112]
e.g. on my mobile:

![1000007487](https://github.com/searchmysite/searchmysite.net/assets/12760482/27f5d5ed-a024-4375-8729-42fb5d7ab617)

I shortened all the drop-down text in https://github.com/searchmysite/searchmysite.net/commit/fa5353d160ae26eb584c5cb67055e884ba175867 and now they should all fit, but it seems in Bootstrap the width is independent of the text contents, i.e. shortening the text didn't shorten the box.

**Comment by squalx** [comment]
Oh man. This one is terrible. I'll fix as soon as I can.

**Comment by m-i-l** [comment]
Many thanks for the fix. Released on production in v1.4.2, and looks good. (Some people might need a browser refresh to pick up the new CSS file.)
