### ISSUE TITLE
Web: Logo and redesign

### ISSUE THREAD

**Issue by m-i-l** [searchmysite/searchmysite.net#28]
The current design was meant to be temporary just to get something working, so is pretty plain Bootstrap. I don't think the final design should be especially exciting given it is supposed to be a back-to-basics search engine, but it could look a bit more slick/professional.

It would also be nice to have a logo. I did experiment with layering bootstrap icon's bi-search on bi-person on bi-globe2 (quite literally "search" "my" "site") but it didn't look so good at 32x32. I also quite liked the concept of the silhouette of a bird foraging for food, but couldn't find a good free icon (in fact many of the ones with the birds heads bent down looked a bit odd so maybe its just a bad idea).

The favicon.ico has kindly been provided by @binyamin .

**Comment by squalx** [comment]
I will take this one on, as we discussed via email. :-)

**Comment by m-i-l** [comment]
New design now rolled out on both https://searchmysite.net/ and https://blog.searchmysite.net/ . Some further details in https://blog.searchmysite.net/posts/introducing-the-redesign-and-first-major-open-source-contributor/ . Many thanks Lucas!
