### ISSUE TITLE
Autofocus in search field on 'Browse Pages'/'Newest Pages'

### ISSUE THREAD

**Issue by rkta** [searchmysite/searchmysite.net#30]
When browsing 'Browse Pages'/'Newest Pages' the cursor is always placed
in the search box. This breaks key-based navigation, e.g. hitting space
bar to scroll down.

After clicking on these links the user clearly intended to not use the
search, so I'd say not auto focussing the search should be the default.

**Comment by m-i-l** [comment]
I've removed the autofocus from all but the initial home page, i.e. I've removed it from the Browse Sites, Newest Pages, and also from the results page, so the keyboard shortcuts should now work on all the pages where you may want to use the keyboard to scroll. Thanks for taking the time to log the issue.
