### ISSUE TITLE
Enable alternate payment methods in addition to credit cards

### ISSUE THREAD

**Issue by m-i-l** [searchmysite/searchmysite.net#33]
At the moment, payment for the verified listing fee is via Stripe, and just accepts credit cards. However, in many countries, e.g. Germany, credit card adoption isn't high (see https://stripe.com/en-gb/payments/payment-methods-guide ). Should investigate and if necessary enable alternate payment mechanisms.

Not a priority at the moment though - the main focus is on building the system out, increasing adoption, and testing whether a search engine can be sustained by anything other than advertising.

**Comment by rkta** [comment]
Would PayPal be an option? One of the reasons for not having a credit card is that there is usually a fee which you have to pay regardless of usage. PayPal is free. At least in my bubble most people have PayPal.

**Comment by m-i-l** [comment]
The current Stripe integration actually includes support for both Google Pay and Apple Pay, and it turns out that these support a number of alternate payment mechanisms, e.g. bank accounts and (in some countries) PayPal. According to https://support.apple.com/en-gb/HT202631#methods Apple Pay has support for PayPal in Germany, and according to https://en.wikipedia.org/wiki/Google_Pay Google Pay also has support for PayPal in Germany.

The Google Pay or Apple Pay button appears just above the "-- Or pay with card --" text on the payment screen - see https://stripe.com/docs/payments/accept-a-payment for a screen grab showing the Apple Pay button. Note that not all users/devices will show the Google Pay or Apple Pay buttons - you need to be running an Apple OS and Apple browser plus have a valid Apple Pay account to see the Apple Pay button, and need to be running Chrome or Safari and have a valid Google Pay account to see the Google Pay button (see https://stripe.com/docs/payments/accept-a-payment#testing-apple-pay-google-pay for full details of requirements to see the buttons).

I've just tested it out on non-prod myself. I don't see an Apple Pay button because I'm not running an Apple OS etc., but I do see a Google Pay button using Chrome on Linux, and using that does work for me at least on non-prod.

So I'm going to close this ticket, because I think that should cover most major non-credit/debit card use cases.
