### ISSUE TITLE
500 response from API when query string has more than one word

### ISSUE THREAD

**Issue by sbw** [searchmysite/searchmysite.net#52]
All API requests with an encoded space respond 500,  Examples:

https://searchmysite.net/api/v1/search/sbw.org?q=a%20b

https://searchmysite.net/api/v1/search/sbw.org?q=a+b

The response content:

```json
{"message": "Internal Server Error"}
```

**Comment by m-i-l** [comment]
Apologies, fixed now.

**Comment by sbw** [comment]
Thanks for the quick response!
