### ISSUE TITLE
General: Build a community

### ISSUE THREAD

**Issue by m-i-l** [searchmysite/searchmysite.net#6]
It would be great to get some good discussion going on the future direction of searchmysite.net, before spending too much more time developing it further. Not sure the best way to do this. Perhaps a https://www.discourse.org/ instance, or a https://discord.com/ group, or something else.

**Comment by m-i-l** [comment]
I've set up https://github.com/searchmysite/searchmysite.net/discussions as a start.

**Comment by Kohoshi12** [comment]
Maybe a community on XMPP, Matrix or a Lemmy instance would be interesting. All libre and open source.

**Comment by m-i-l** [comment]
Thanks for taking the time to make a suggestion. XMPP, Matrix and Lemmy look good, although they would need to have server instances set up, and I was thinking in terms of something a bit simpler, given that it is just to get ideas and feedback rather than be a core part of the system/service. I do have a Mastodon account BTW, where I (periodically) post about things relating to this project - there's a link on https://searchmysite.net/admin/contact/ .

**Comment by ScootRay** [comment]
Per my other message, I suggest placing a link to the discussion forum from the search engine page to draw more folks into it. 

Ray

**Comment by m-i-l** [comment]
> Per my other message, I suggest placing a link to the discussion forum from the search engine page to draw more folks into it.
> 
> Ray

Thanks. Logged as https://github.com/searchmysite/searchmysite.net/issues/36 .

**Comment by m-i-l** [comment]
Link to discussion forum, i.e. #36 , added to footer.

Some discussion of building a community at https://blog.searchmysite.net/posts/searchmysite.net-retrospective-and-future-plans/#not-managed-to-build-a-community-of-people-interested-in-building-a-better-internet-search .

Closing for now.
